lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
permalink: /posts/:title/
exclude:
  - "Gemfile*"
  - "CNAME"
  - "README.md"
  - "script/*"
  - "vendor"
  - ".travis.yml"
url: "http://www.matthorn.tech"
repository: mathphreak/mathphreak.github.io
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
feed:
  path: feed.atom
title: Matt Horn
collections:
  - repo_info
author:
  name: Matt Horn
  uri: http://www.matthorn.tech
