lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
permalink: /posts/:title/
exclude:
 - "Gemfile*"
 - "CNAME"
 - "README.md"
 - "script/*"
 - "vendor"
url: "http://www.matthorn.tech"
gems:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
feed:
  path: feed.atom
title: Matt Horn
collections:
  - repo_info
